format = """
$username\
$hostname\
$directory\
$git_branch\
$fill\
$python\
$cmd_duration\
$line_break\
$character"""

[directory]
format = "[$path]($style) "
truncation_length = 3
truncation_symbol = "~/..../"
style = "fg:#f5d0f0"

[character]
disabled = false
success_symbol = '[❯](bold fg:white)'
error_symbol = '[❯](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:white)'
vimcmd_replace_one_symbol = '[❮](bold fg:lavender)'
vimcmd_replace_symbol = '[❮](bold fg:lavender)'
vimcmd_visual_symbol = '[❮](bold fg:yellow)'

[git_branch]
format = "[$symbol $branch]($style) "
style = "fg:#8ea9fa"
symbol = ""

[fill]
symbol = " "

[cmd_duration]
format = "| [$duration]($style) "

[python]
format = "[$virtualenv $version]($style)"
style = "bright-black"